package voxspell.newquiz;

/**
 * Interface to be implemented by classes whose instances need to be notified
 * of changes to a QuizModel. A QuizModel calls method update() on all
 * registered QuizModelListeners whenever its state changes.
 * 
 * Declaration: Code adapted from 251 assignment.
 * 
 */
public interface QuizModelListener {
	/**
	 * Notifies a QuizModelListener that a QuizModel that it has registered 
	 * interest in has generated an event of interest.
	 * @param event of interest that has been generated by the QuizModel
	 */
	void updateView(QuizModelEvent.EventType eventType);
}
